# Enquete competition - mise à jour auto

In [1]:
# import gspread as gs

# import pandas as pd

# gc = gs.service_account('/home/explore/.config/gspread/credentials.json')
# COMPET_LISTE = 'https://docs.google.com/spreadsheets/d/1T7XNl3VUjsanvH7UOWEVa4tyfJUBSLFWVVJHUswXrCM/edit?usp=sharing'

# sh = gc.open_by_url(COMPET_LISTE)

# Enquete Competition

Telechargement au format xlsx depuis 'https://docs.google.com/spreadsheets/d/1T7XNl3VUjsanvH7UOWEVa4tyfJUBSLFWVVJHUswXrCM/edit?usp=sharing'

Creation du lien symbolique e.g. `ln -s Competition 2022-23\ (réponses).xlsx Competition.xlsx`

In [2]:
import pandas as pd
enquete_filename = 'Competition.xlsx'

In [3]:
competiteurs = pd.read_excel(enquete_filename)
competiteurs.head()

,Horodateur,Adresse e-mail,Prénom Nom,Je suis intéressé par les tournois,Je suis intéressé par les interclubs,Je suis interessé par les interclubs et en + je veux être le capitaine de l'équipe !,Commentaires et/ou questions
0,2022-10-05 18:37:57.780,guillaume.ramelet@gmail.com,Guillaume Ramelet,Oui,Oui,pas du tout,good job
1,2022-10-05 18:42:43.401,nicovidal@orange.fr,Nicolas Vidal,Oui,Oui,Un peu,NaN
2,2022-10-05 18:43:30.795,aurelien83300@hotmail.fr,Aurélien Meyrignac,Oui,Oui,Un peu,NaN
3,2022-10-05 18:43:41.989,amelielarque@gmail.com,Larque,Oui,Non,NaN,NaN
4,2022-10-05 18:44:18.212,jeanmarie.boulat@gmail.com,Jean-Marie Boulat,Oui,Oui,pas du tout,NaN

# Fichier adherents + classement

In [4]:
import pandas as pd
adherents_filename = 'xls633be4e053e80.xlsx'

In [5]:
pd.read_excel(adherents_filename).head()

,Nom d'usage,Prénom,Licence,Date de naissance,Email de contact,Tél. de contact,Saison,Adhérent validé,Catégorie
0,AIGUADEL-JALEME,Pascal,7254760,01-10-1973,bosslaidealj@gmail.com,3.363477e+10,22-23,Oui,Veteran 3
1,ALONSO MARTINEZ,Lana,7451860,21-10-2006,lana-fred@hotmail.fr,NaN,22-23,Non,Junior 1
2,ANDRAL,Anthony,7354056,09-08-1989,anthonyandral@gmail.com,3.362213e+10,22-23,Oui,Senior
3,ASSELINEAU,Dorian,7354558,10-05-2010,karinecesar@gmail.com,3.368452e+10,22-23,Non,Minime 1
4,AURIERES,Vivien,7386012,21-09-1979,labidoche1@hotmail.fr,3.368702e+10,22-23,Oui,Veteran 2

In [6]:
from rbc import add_classements

In [7]:
adherents = add_classements(pd.read_excel(adherents_filename))
adherents.head()

,Nom d'usage,Prénom,Licence,Date de naissance,Email de contact,Tél. de contact,Saison,Adhérent validé,Catégorie,Classement,S,D,M
0,AIGUADEL-JALEME,Pascal,7254760,01-10-1973,bosslaidealj@gmail.com,3.363477e+10,22-23,Oui,Veteran 3,,-,-,-
1,ALONSO MARTINEZ,Lana,7451860,21-10-2006,lana-fred@hotmail.fr,NaN,22-23,Non,Junior 1,,-,-,-
2,ANDRAL,Anthony,7354056,09-08-1989,anthonyandral@gmail.com,3.362213e+10,22-23,Oui,Senior,P11/P10/P10,P11,P10,P10
3,ASSELINEAU,Dorian,7354558,10-05-2010,karinecesar@gmail.com,3.368452e+10,22-23,Non,Minime 1,,-,-,-
4,AURIERES,Vivien,7386012,21-09-1979,labidoche1@hotmail.fr,3.368702e+10,22-23,Oui,Veteran 2,,-,-,-

In [8]:
adherents.Catégorie.unique()

array(['Veteran 3', 'Junior 1', 'Senior', 'Minime 1', 'Veteran 2',
       'Veteran 6', 'Minibad', 'Veteran 1', 'Benjamin 2', 'Cadet 1',
       'Veteran 5', 'Junior 2', 'Benjamin 1', 'Veteran 4', 'Poussin 1',
       'Cadet 2', 'Minime 2', 'Veteran 9'], dtype=object)

In [9]:
adherents_adultes = adherents[~adherents.Catégorie.isin(['Junior 1', 'Minime 1', 'Minibad', 'Benjamin 2', 'Cadet 1', 'Junior 2', 'Benjamin 1', 'Poussin 1',    'Cadet 2', 'Minime 2'])]

In [10]:
adherents_adultes.head()

,Nom d'usage,Prénom,Licence,Date de naissance,Email de contact,Tél. de contact,Saison,Adhérent validé,Catégorie,Classement,S,D,M
0,AIGUADEL-JALEME,Pascal,7254760,01-10-1973,bosslaidealj@gmail.com,3.363477e+10,22-23,Oui,Veteran 3,,-,-,-
2,ANDRAL,Anthony,7354056,09-08-1989,anthonyandral@gmail.com,3.362213e+10,22-23,Oui,Senior,P11/P10/P10,P11,P10,P10
4,AURIERES,Vivien,7386012,21-09-1979,labidoche1@hotmail.fr,3.368702e+10,22-23,Oui,Veteran 2,,-,-,-
5,AUTHEMAN,Jerome,6705650,15-04-1975,emergency@live.fr,3.378298e+10,22-23,Oui,Veteran 3,,-,-,-
6,AVARGUEZ,Eric,6630518,17-09-1958,presidencerbc63@gmail.com,3.366998e+10,22-23,Oui,Veteran 6,P11/D9/P10,P11,D9,P10

In [11]:
print(f"Adherents adulte: {adherents_adultes.shape[0]}")

Adherents adulte: 91

# Merge des fichiers

In [12]:
adherents_adultes = adherents_adultes.copy()
adherents_adultes["Email de contact"] = adherents_adultes["Email de contact"].str.lower()
competiteurs["Adresse e-mail"] = competiteurs["Adresse e-mail"].str.lower()

result = pd.merge(adherents_adultes, competiteurs, how="right", left_on="Email de contact", right_on="Adresse e-mail")

In [13]:
print(f"Nombre adherents : {adherents_adultes.shape[0]}, Nombre competiteurs : {competiteurs.shape[0]}, Nombre liaison : {result.shape[0]}")
print(f"Pourcentage de liaison: {100*result.shape[0]/competiteurs.shape[0]:0.02f}")

Nombre adherents : 91, Nombre competiteurs : 34, Nombre liaison : 34
Pourcentage de liaison: 100.00

In [14]:
competiteurs.head()

,Horodateur,Adresse e-mail,Prénom Nom,Je suis intéressé par les tournois,Je suis intéressé par les interclubs,Je suis interessé par les interclubs et en + je veux être le capitaine de l'équipe !,Commentaires et/ou questions
0,2022-10-05 18:37:57.780,guillaume.ramelet@gmail.com,Guillaume Ramelet,Oui,Oui,pas du tout,good job
1,2022-10-05 18:42:43.401,nicovidal@orange.fr,Nicolas Vidal,Oui,Oui,Un peu,NaN
2,2022-10-05 18:43:30.795,aurelien83300@hotmail.fr,Aurélien Meyrignac,Oui,Oui,Un peu,NaN
3,2022-10-05 18:43:41.989,amelielarque@gmail.com,Larque,Oui,Non,NaN,NaN
4,2022-10-05 18:44:18.212,jeanmarie.boulat@gmail.com,Jean-Marie Boulat,Oui,Oui,pas du tout,NaN

In [15]:
result.head()

,Nom d'usage,Prénom,Licence,Date de naissance,Email de contact,Tél. de contact,Saison,Adhérent validé,Catégorie,Classement,S,D,M,Horodateur,Adresse e-mail,Prénom Nom,Je suis intéressé par les tournois,Je suis intéressé par les interclubs,Je suis interessé par les interclubs et en + je veux être le capitaine de l'équipe !,Commentaires et/ou questions
0,RAMELET,Guillaume,387835.0,27-06-1976,guillaume.ramelet@gmail.com,3.363719e+10,22-23,Oui,Veteran 3,P10/D8/D9,P10,D8,D9,2022-10-05 18:37:57.780,guillaume.ramelet@gmail.com,Guillaume Ramelet,Oui,Oui,pas du tout,good job
1,VIDAL,Nicolas,7428333.0,09-11-1993,nicovidal@orange.fr,3.365941e+10,22-23,Oui,Senior,NC/NC/NC,NC,NC,NC,2022-10-05 18:42:43.401,nicovidal@orange.fr,Nicolas Vidal,Oui,Oui,Un peu,NaN
2,MEYRIGNAC,Aurélien,6995597.0,01-03-1987,aurelien83300@hotmail.fr,3.366123e+10,22-23,Oui,Veteran 1,P10/D9/D9,P10,D9,D9,2022-10-05 18:43:30.795,aurelien83300@hotmail.fr,Aurélien Meyrignac,Oui,Oui,Un peu,NaN
3,LARQUE,Amelie,7036423.0,15-12-1982,amelielarque@gmail.com,3.361981e+10,22-23,Oui,Veteran 2,P11/D9/D9,P11,D9,D9,2022-10-05 18:43:41.989,amelielarque@gmail.com,Larque,Oui,Non,NaN,NaN
4,BOULAT,Jean-marie,7348450.0,15-06-1989,jeanmarie.boulat@gmail.com,3.364590e+10,22-23,Oui,Senior,D9/D9/P10,D9,D9,P10,2022-10-05 18:44:18.212,jeanmarie.boulat@gmail.com,Jean-Marie Boulat,Oui,Oui,pas du tout,NaN

In [16]:
result.to_excel('competiteurs.xlsx')